Repository jenkins-x/cloud-environments, pull requests merged in 2018-11, with the labels that each got.

#214 fix: try to use the internal repo for charts
  Makefile
Labels: approved, size/XS

#213 fix: updated bucket name to be the correct GCS bucket
  env-jx-infra/myvalues.yaml
Labels: approved, size/XS

#218 fix: removed references to depreacted chartmuseum instance
  Makefile
Labels: approved, size/XS

#222 add Gareth Evans gpg so he can decrypt secrets and install the Jenkins X infra
  env-jx-infra/.sops.yaml
  env-jx-infra/secrets.yaml
Labels: approved, size/L

#223 added chartmuseum secret into jx-infra
  env-jx-infra/secrets.yaml
Labels: approved, size/L

#227 update secrets with new bot token
  env-jx-infra/secrets.yaml
Labels: size/L
