Repository jenkins-x/cloud-environments, pull requests merged in 2018-10, with the labels that each got.

#193 disable docker registry by default on EKS
  env-eks/myvalues.yaml
Labels: approved, size/XS

#194 feat: Support for IBM Cloud Kubernetes Service
  env-ibm/README.md
  env-iks/Makefile
  env-iks/README.md
  env-iks/myvalues.yaml
  env-iks/secrets.yaml
Labels: approved, size/L

#202 Add IBM Cloud Private environment
  env-icp/Makefile
  env-icp/README.md
  env-icp/myvalues.yaml
  env-icp/secrets.yaml
Labels: approved, size/M
