Repository jenkins-x/cloud-environments, pull requests merged in 2019-01, with the labels that each got.

#246 change maven settings to use nexus group not public and fix jenkins repo server creds
  env-jx-infra/secrets.yaml
Labels: size/L

#249 add extra CoreGKESA serviceaccount secret
  env-jx-infra/secrets.yaml
Labels: size/L

#252 Added kaniko secret jx-infra
  env-jx-infra/secrets.yaml
Labels: approved, size/L

#251 WIP: chore: try move to new bdd tests
  .gitignore
  Jenkinsfile
  Makefile
  jx/bdd/clusters.yaml
  jx/bdd/gitops.yaml
  jx/bdd/prow.yaml
  jx/scripts/bdd.sh
  sethome.sh
Labels: do-not-merge/work-in-progress, size/M
